# Generated by Django 5.2.8 on 2025-11-25 00:40

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_attribution', models.DateTimeField(blank=True, null=True)),
                ('attribue_par', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='permissions_attribuees', to=settings.AUTH_USER_MODEL)),
                ('id_permission', models.ForeignKey(on_delete=models.PROTECT, related_name='roles', to='api.permission')),
                ('id_role', models.ForeignKey(on_delete=models.PROTECT, related_name='permissions', to='api.role')),
            ],
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('id_role', 'id_permission'), name='unique_role_permission'),
        ),
    ]
