# Generated by Django 5.1.2 on 2025-12-03 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models, connection


def _add_column_if_missing(table_name: str, column_name: str, add_field_callable):
    with connection.cursor() as cursor:
        existing_columns = {col.name for col in connection.introspection.get_table_description(cursor, table_name)}
    if column_name in existing_columns:
        return
    add_field_callable()


def add_agent_traitant_boncommande(apps, schema_editor):
    def _add():
        BonCommande = apps.get_model('api', 'BonCommande')
        field = BonCommande._meta.get_field('agent_traitant')
        schema_editor.add_field(BonCommande, field)

    _add_column_if_missing('api_boncommande', 'agent_traitant_id', _add)


def add_agent_traitant_demande(apps, schema_editor):
    def _add():
        Demande = apps.get_model('api', 'Demande')
        field = Demande._meta.get_field('agent_traitant')
        schema_editor.add_field(Demande, field)

    _add_column_if_missing('api_demande', 'agent_traitant_id', _add)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='boncommande',
                    name='agent_traitant',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='bons_commande_traitees',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_agent_traitant_boncommande, reverse_code=migrations.RunPython.noop),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='demande',
                    name='agent_traitant',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='demandes_traitees',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(add_agent_traitant_demande, reverse_code=migrations.RunPython.noop),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
