# Generated by Django 5.1.2 on 2025-12-03 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommande',
            name='agent_traitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande_traitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demande',
            name='agent_traitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
