# Generated by Django 5.1.2 on 2025-12-30 14:34

import django.db.models.deletion
from django.db import migrations, models


def set_demande_fournisseur(apps, schema_editor):
    Demande = apps.get_model('api', 'Demande')
    LigneDemande = apps.get_model('api', 'LigneDemande')
    for demande in Demande.objects.filter(id_fournisseur__isnull=True):
        fournisseur_id = (
            LigneDemande.objects.filter(id_demande=demande, id_fournisseur__isnull=False)
            .values_list('id_fournisseur_id', flat=True)
            .first()
        )
        if fournisseur_id:
            demande.id_fournisseur_id = fournisseur_id
            demande.save(update_fields=['id_fournisseur'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='id_fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='api.fournisseur'),
        ),
        migrations.RunPython(set_demande_fournisseur, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='lignedemande',
            name='id_fournisseur',
        ),
    ]
