# Generated by Django 5.1.2 on 2025-12-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='rapport_daa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
