# Generated by Django 5.1.2 on 2025-12-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_lignedemande_id_fournisseur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturenumerique',
            name='certificat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='signaturenumerique',
            name='empreinte',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
