# Generated by Django 5.1.2 on 2025-11-26 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_permission_rolepermission'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
    ]
