# Generated by Django 5.1.2 on 2025-12-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_demande_description_alter_demande_rapport_daa'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='priorite',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
    ]
