# Generated by Django 5.1.2 on 2025-12-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_boncommande_agent_traitant_demande_agent_traitant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='chemin_fichier',
            field=models.FileField(max_length=500, upload_to='documents/'),
        ),
    ]
