# Generated by Django 5.1.2 on 2025-12-08 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_document_priorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='utilisateurs_transferts',
            field=models.ManyToManyField(blank=True, related_name='demandes_transferees', to=settings.AUTH_USER_MODEL),
        ),
    ]
