# Generated by Django 5.1.2 on 2025-12-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_signaturenumerique_certificat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignebc',
            name='prix_net',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
