# Generated by Django 5.1.2 on 2025-11-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_utilisateur_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='source',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
