# Generated by Django 5.1.2 on 2025-12-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_document_chemin_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfert',
            name='raison',
            field=models.TextField(blank=True, null=True),
        ),
    ]
