# Generated by Django 5.1.2 on 2025-12-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_demande_utilisateurs_transferts'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommandeSequence',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Séquence bon de commande',
                'verbose_name_plural': 'Séquences bons de commande',
            },
        ),
    ]
