# Generated by Django 5.1.2 on 2026-01-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_lignebc_prix_net'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='id_ligne_budgetaire',
            field=models.CharField(blank=True, db_column='id_ligne_budgetaire_id', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='boncommande',
            name='montant_engage',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=18),
        ),
    ]
