# Generated by Django 5.1.2 on 2025-12-03 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_transfert_raison'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type_article',
            field=models.CharField(choices=[('article', 'Article'), ('service', 'Service')], default='article', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='id_categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='api.categorie'),
        ),
    ]
