# Generated by Django 5.1.2 on 2025-12-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_article_type_article_alter_article_id_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='peut_rediger',
            field=models.BooleanField(default=False),
        ),
    ]
