# Generated by Django 5.1.2 on 2025-12-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_boncommandesequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_sequence', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sequence document',
                'verbose_name_plural': 'Sequences documents',
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='reference_fonctionnelle',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
