# Generated by Django 5.1.2 on 2026-01-07 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_boncommande_id_ligne_budgetaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='date_signature',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='decision',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuve'), ('refuse', 'Refuse')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='demande',
            name='id_document_preuve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_signature', to='api.document'),
        ),
        migrations.AddField(
            model_name='demande',
            name='id_signataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demandes_signees', to=settings.AUTH_USER_MODEL),
        ),
    ]
