# Generated by Django 5.1.2 on 2025-12-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_utilisateur_peut_rediger'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='peut_signer',
            field=models.BooleanField(default=False),
        ),
    ]
