# Generated by Django 5.2.8 on 2025-12-24 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_document_sequence_reference_fonctionnelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='canal',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='document',
            name='code',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='titre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='chemin_fichier',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='documents/'),
        ),
        migrations.CreateModel(
            name='SignatureUtilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature', models.FileField(blank=True, null=True, upload_to='signatures/')),
                ('cachet', models.FileField(blank=True, null=True, upload_to='cachets/')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signature_utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'signature utilisateur',
                'verbose_name_plural': 'signatures utilisateurs',
            },
        ),
    ]
