# Generated by Django 5.1.2 on 2025-12-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_utilisateur_peut_signer'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='rapport_daa',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
