# Generated by Django 5.1.2 on 2025-12-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dates_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='lieu_livraison',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
