# Generated by Django 5.1.2 on 2025-12-01 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_boncommande_lieu_livraison'),
        ('api', '0011_alter_departement_unique'),
    ]

    operations = [
    ]
