# Generated by Django 5.1.2 on 2025-12-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20251201_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boncommande',
            name='numero_bc',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
