"""
Django settings for SGBC project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
from datetime import datetime, timedelta
#import dj_database_url
import os
from pathlib import Path
from django.contrib.messages import constants as messages
import os
# Import pour les variables d'environnement
try:
    from dotenv import load_dotenv
    # Charger les variables d'environnement depuis le fichier .env
    load_dotenv()
except ImportError:
    # python-dotenv n'est pas installé, utiliser seulement les variables d'environnement système
    pass

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# IMPORTANT: La clé secrète ne devrait JAMAIS être codée en dur dans le code source
# Utilisez une variable d'environnement pour stocker cette clé de manière sécurisée
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG doit être False en production pour éviter de divulguer des informations sensibles
# Utilisez une variable d'environnement pour contrôler cette valeur
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

    
allowed_hosts_env = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0,127.0.0.1:8000')
_hosts = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()]
ALLOWED_HOSTS = []
for host in _hosts:
    ALLOWED_HOSTS.append(host)
    if ':' in host:
        # Ajoute la partie sans port pour éviter les erreurs DisallowedHost
        ALLOWED_HOSTS.append(host.split(':', 1)[0])
for host in ('127.0.0.1', 'localhost', '0.0.0.0'):
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'api',
]





# Configuration CORS (Cross-Origin Resource Sharing)
# Définit les origines autorisées à faire des requêtes vers votre API
CORS_ALLOWED_ORIGINS = [
    # Développement local
    "http://localhost:3000",
    "http://localhost:3001",
    "http://localhost:8080",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8080",
    "https://e2c-henna.vercel.app",
    "https://sgbc.aa-ce.org",
    "https://www.costafric.com",
    "https://e2c-henna.vercel.app/auth/login"
]

# Configuration CSRF pour les origines de confiance
# IMPORTANT: Nécessaire pour que Django accepte les requêtes POST depuis ces domaines
CSRF_TRUSTED_ORIGINS = [
    'https://api.sgbc.aa-ce.org/',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]


CSRF_ALLOWED_ORIGINS = CSRF_TRUSTED_ORIGINS

CORS_ORIGINS_WHITELIST = CSRF_TRUSTED_ORIGINS

# Configuration CORS détaillée
# ⚠️ DÉVELOPPEMENT UNIQUEMENT : Authoriser toutes les origines si en mode DEBUG
# Autorise tout en développement, sécurisé en production
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Permettre les credentials (cookies, authorization headers)
CORS_ALLOW_CREDENTIALS = True

# Préflight requests cache (en secondes)
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 heures

CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'api.middleware.AuditAllMiddleware',
]

ROOT_URLCONF = 'SGBC.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SGBC.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Brazzaville'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'api.Utilisateur'

# CORS
CORS_ALLOW_ALL_ORIGINS = True

# DRF / Auth
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

SIMPLE_JWT = {
    # Durée de validité de l'access token (3 jours)
    'ACCESS_TOKEN_LIFETIME': timedelta(days=3),
    # Durée de validité du token de rafraîchissement (7 jours)
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
    # Durée de validité du token de rafraîchissement "coulissant" (30 jours)
    'SLIDING_TOKEN_LIFETIME': timedelta(days=30),
    # Période de grâce pour le rafraîchissement du token (1 jour)
    'SLIDING_TOKEN_REFRESH_LIFETIME_GRACE_PERIOD': timedelta(days=1),
    # Durée de validité maximale pour le rafraîchissement du token (30 jours)
    'SLIDING_TOKEN_REFRESH_EXPIRATION_DELTA': timedelta(days=30),
    # Algorithme de chiffrement JWT (HS256 est un choix courant)
    'ALGORITHM': 'HS256',
    # Clé secrète utilisée pour signer les tokens (utilisez la clé secrète de votre projet Django)
    'SIGNING_KEY': SECRET_KEY,
    # Clé de vérification (laissez-la à None pour utiliser la même que la clé de signature)
    'VERIFYING_KEY': None,
    # Type d'en-tête d'authentification à utiliser dans les requêtes (Bearer est courant)
    'AUTH_HEADER_TYPES': ('Bearer',),
}


EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@example.com')
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'false').lower() == 'true'

# SMS (simple configurable backend; default console)
SMS_BACKEND = os.getenv('SMS_BACKEND', 'console')  # console | custom
SMS_SENDER_ID = os.getenv('SMS_SENDER_ID', 'SGBC')
SMS_API_URL = os.getenv('SMS_API_URL', '')
SMS_API_KEY = os.getenv('SMS_API_KEY', '')
